site_name: Cookiecutter Pypackage
site_url: https://m-v-kalashnikov.github.io/cookiecutter-pypackage
repo_url: https://github.com/m-v-kalashnikov/cookiecutter-pypackage
repo_name: m-v-kalashnikov/cookiecutter-pypackage
nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Console script: console_script_setup.md
  - Release checklist: pypi_release_checklist.md
  - FAQ: faq.md
  - History: history.md

theme:
  name: material
  language: en
  #logo: assets/logo.png
#  palette:
#      scheme: preference
#      primary: black
#      accent: pink
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - include-markdown
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/m-v-kalashnikov
      name: Github
    - icon: material/email
      link: "mailto:kalashnikovsystem@gmail.com"
